<?xml version="1.0"?>
<!DOCTYPE PROVINCES [
	<!ELEMENT PROVINCES (BORDER_DEFINITIONS?, PROVINCE+)>
	
	<!-- ===================================================================== -->
	<!ELEMENT BORDER_DEFINITIONS (BORDER+)>
	
	<!ELEMENT BORDER EMPTY>
	<!ATTLIST BORDER	
				id ID #REQUIRED
				description CDATA #REQUIRED
				unitTypes CDATA #IMPLIED
				from CDATA #IMPLIED
				orderTypes CDATA #IMPLIED
				baseMoveModifier CDATA #IMPLIED
				prohibited CDATA #REQUIRED
				>
				
	<!-- ===================================================================== -->
	<!ELEMENT PROVINCE (UNIQUENAME*, ADJACENCY+)>
	<!ATTLIST PROVINCE 	
				shortname CDATA #REQUIRED
				fullname CDATA #REQUIRED
				isConvoyableCoast (true|false) "false"
				borders IDREFS #IMPLIED
				>	
	
				
	<!ELEMENT UNIQUENAME EMPTY>
	<!ATTLIST UNIQUENAME name CDATA #REQUIRED>
	
	<!ELEMENT ADJACENCY EMPTY>
	<!ATTLIST ADJACENCY 	
				type (mv|xc|nc|sc|wc|ec) "mv"
				refs CDATA #REQUIRED
				>
]>
<!-- Chromatic Adjacency file -->
<PROVINCES>
	<PROVINCE fullname="Alabaster" shortname="ala">
		<UNIQUENAME name="alab" />
		<ADJACENCY type="mv" refs="ivo sno"/>
		<ADJACENCY type="xc" refs="ivo lea ice sno"/>
	</PROVINCE>
	<PROVINCE fullname="Aquatic Sea" shortname="aqu">
		<UNIQUENAME name="aqua" />
		<UNIQUENAME name="aquatic" />
		<ADJACENCY type="xc" refs="mag ind sap cer for mal"/>
	</PROVINCE>
	<PROVINCE fullname="Azure" shortname="azu">
		<UNIQUENAME name="azur" />
		<ADJACENCY type="mv" refs="roy col cob"/>
		<ADJACENCY type="xc" refs="roy ind mau col"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Butter" shortname="but">
		<UNIQUENAME name="butter" />
		<UNIQUENAME name="sob" />
		<ADJACENCY type="xc" refs="mal cya top lem sep bro"/>
	</PROVINCE>
	<PROVINCE fullname="Bronze" shortname="bro">
		<UNIQUENAME name="bron" />
		<UNIQUENAME name="bronz" />
		<ADJACENCY type="mv" refs="bro"/>
		<ADJACENCY type="xc" refs="umb nig sep but"/>
	</PROVINCE>
	<PROVINCE fullname="Carnation Sea" shortname="car">
		<UNIQUENAME name="carn" />
		<UNIQUENAME name="carnat" />
		<UNIQUENAME name="carnation" />
		<ADJACENCY type="xc" refs="ros fir cri ver lav gar che"/>
	</PROVINCE>
	<PROVINCE fullname="Cerulean" shortname="cer">
		<UNIQUENAME name="cerul" />
		<UNIQUENAME name="cerrulean" />
		<UNIQUENAME name="cerrullean" />
		<UNIQUENAME name="cerullean" />
		<ADJACENCY type="mv" refs="cob sap roy"/>
		<ADJACENCY type="xc" refs="cob for aqu sap"/>
	</PROVINCE>
	<PROVINCE fullname="Chalk" shortname="cha">
		<UNIQUENAME name="chal" />
		<ADJACENCY type="mv" refs="ivo pap gho"/>
		<ADJACENCY type="xc" refs="ivo lea pla pap"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Cherries" shortname="che">
		<UNIQUENAME name="cherries" />
		<UNIQUENAME name="cherry" />
		<UNIQUENAME name="soh" />
		<ADJACENCY type="xc" refs="ice sno gho ros car gar"/>
	</PROVINCE>
	<PROVINCE fullname="Coal" shortname="coa">
		<ADJACENCY type="mv" refs="obs jet ebo"/>
		<ADJACENCY type="xc" refs="jet mer nig obs"/>
	</PROVINCE>
	<PROVINCE fullname="Cobalt" shortname="cob">
		<UNIQUENAME name="cobal" />
		<UNIQUENAME name="cobolt" />
		<UNIQUENAME name="cobol" />
		<UNIQUENAME name="co" />
		<ADJACENCY type="mv" refs="azu roy col cer saf"/>
		<ADJACENCY type="xc" refs="cer for eme saf"/>
	</PROVINCE>
	<PROVINCE fullname="Cold" shortname="col">
		<ADJACENCY type="mv" refs="azu cob saf cry hot rub"/>
		<ADJACENCY type="xc" refs="mau azu rub"/>
	</PROVINCE>
	<PROVINCE fullname="Crimson" shortname="cri">
		<UNIQUENAME name="crim" />
		<ADJACENCY type="mv" refs="fir ver rub mar"/>
		<ADJACENCY type="xc" refs="fir car ver"/>
	</PROVINCE>
	<PROVINCE fullname="Crystal" shortname="cry">
		<UNIQUENAME name="xta" />
		<UNIQUENAME name="xtal" />
		<ADJACENCY type="mv" refs="saf ink pap hot col"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Cyan" shortname="cya">
		<UNIQUENAME name="cyan" />
		<UNIQUENAME name="cyanide" />
		<UNIQUENAME name="cyanic" />
		<ADJACENCY type="xc" refs="eme sul gol top but mal for"/>
	</PROVINCE>
	<PROVINCE fullname="Ebony" shortname="ebo">
		<UNIQUENAME name="ebon" />
		<ADJACENCY type="mv" refs="rav obs jet coa"/>
		<ADJACENCY type="xc" refs="rav umb obs"/>
	</PROVINCE>
	<PROVINCE fullname="Bay of Emeralds" shortname="eme">
		<UNIQUENAME name="emer" />
		<UNIQUENAME name="emerald" />
		<UNIQUENAME name="emeralds" />
		<UNIQUENAME name="boe" />
		<UNIQUENAME name="bayofe" />
		<ADJACENCY type="xc" refs="saf sul cya for cob"/>
	</PROVINCE>
	<PROVINCE fullname="Fire Engine" shortname="fir">
		<UNIQUENAME name="eng" />
		<UNIQUENAME name="fire" />
		<UNIQUENAME name="engine" />
		<UNIQUENAME name="fireengine" />
		<ADJACENCY type="mv" refs="cri hot rub"/>
		<ADJACENCY type="xc" refs="cri car ros hot"/>
	</PROVINCE>
	<PROVINCE fullname="Forest Sea" shortname="for">
		<UNIQUENAME name="fore" />
		<UNIQUENAME name="forest" />
		<ADJACENCY type="xc" refs="aqu cer cob eme cya mal"/>
	</PROVINCE>
	<PROVINCE fullname="Garnet" shortname="gar">
		<UNIQUENAME name="garn" />
		<ADJACENCY type="mv" refs="gar"/>
		<ADJACENCY type="xc" refs="car lav che ice"/>
	</PROVINCE>
	<PROVINCE fullname="Ghost" shortname="gho">
		<UNIQUENAME name="ghostbusters" />
		<ADJACENCY type="mv" refs="cha ivo pap sno hot"/>
		<ADJACENCY type="xc" refs="sno che ros hot"/>
	</PROVINCE>
	<PROVINCE fullname="Gold" shortname="gol">
		<UNIQUENAME name="au" />
		<ADJACENCY type="mv" refs="sul top sun lem"/>
		<ADJACENCY type="xc" refs="sul cya top"/>
	</PROVINCE>
	<PROVINCE fullname="Gulf of Hazel" shortname="haz">
		<UNIQUENAME name="hazel" />
		<UNIQUENAME name="hazelnuts" />
		<UNIQUENAME name="goh" />
		<UNIQUENAME name="gulfofh" />
		<ADJACENCY type="xc" refs="ink rav umb sep sun"/>
	</PROVINCE>
	<PROVINCE fullname="Hot" shortname="hot">
		<ADJACENCY type="mv" refs="fir rub col cry pap gho"/>
		<ADJACENCY type="xc" refs="ros fir gho"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Ice" shortname="ice">
		<UNIQUENAME name="iceland" />
		<UNIQUENAME name="iceberg" />
		<UNIQUENAME name="soi" />
		<UNIQUENAME name="h2o" />
		<ADJACENCY type="xc" refs="sil lea ala sno che gar"/>
	</PROVINCE>
	<PROVINCE fullname="Indigo Sea" shortname="ind">
		<UNIQUENAME name="indigo" />
		<ADJACENCY type="xc" refs="mau azu roy sap aqu mag vio"/>
	</PROVINCE>
	<PROVINCE fullname="Ink" shortname="ink">
		<UNIQUENAME name="inkwell" />
		<UNIQUENAME name="inkjet" />
		<ADJACENCY type="mv" refs="rav jet pap cry saf sun"/>
		<ADJACENCY type="xc" refs="haz rav sun"/>
	</PROVINCE>
	<PROVINCE fullname="Ivory" shortname="ivo">
		<UNIQUENAME name="ivor" />
		<ADJACENCY type="mv" refs="cha ala gho sno"/>
		<ADJACENCY type="xc" refs="cha lea ala"/>
	</PROVINCE>
	<PROVINCE fullname="Jet" shortname="jet">
		<UNIQUENAME name="747" />
		<UNIQUENAME name="jumbojet" />
		<ADJACENCY type="mv" refs="rav ebo ink coa pap"/>
		<ADJACENCY type="xc" refs="coa mer pla pap"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Lava" shortname="lav">
		<UNIQUENAME name="lava" />
		<UNIQUENAME name="sol" />
		<ADJACENCY type="xc" refs="gar car ver mar vio mag"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Lead" shortname="lea">
		<UNIQUENAME name="lead" />
		<UNIQUENAME name="sop" />
		<UNIQUENAME name="pb" />
		<ADJACENCY type="xc" refs="pla cha ivo ala ice sil mer"/>
	</PROVINCE>
	<PROVINCE fullname="Lemon" shortname="lem">
		<UNIQUENAME name="lemo" />
		<ADJACENCY type="mv" refs="sun top gol"/>
		<ADJACENCY type="xc" refs="sun sep but top"/>
	</PROVINCE>
	<PROVINCE fullname="Magenta" shortname="mag">
		<UNIQUENAME name="mage" />
		<ADJACENCY type="mv" refs="mag"/>
		<ADJACENCY type="xc" refs="ind aqu vio lav"/>
	</PROVINCE>
	<PROVINCE fullname="Malachite" shortname="mal">
		<UNIQUENAME name="malac" />
		<UNIQUENAME name="malach" />
		<ADJACENCY type="mv" refs="mal"/>
		<ADJACENCY type="xc" refs="aqu cya but for"/>
	</PROVINCE>
	<PROVINCE fullname="Maroon" shortname="mar">
		<ADJACENCY type="mv" refs="rub ver cri"/>
		<ADJACENCY type="xc" refs="rub vio lav ver"/>
	</PROVINCE>
	<PROVINCE fullname="Gulf of Mauve" shortname="mau">
		<UNIQUENAME name="mauve" />
		<UNIQUENAME name="gom" />
		<ADJACENCY type="xc" refs="col azu ind vio rub"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Mercury" shortname="mer">
		<UNIQUENAME name="merc" />
		<UNIQUENAME name="mercury" />
		<UNIQUENAME name="mercedes" />
		<UNIQUENAME name="som" />
		<UNIQUENAME name="hg" />
		<ADJACENCY type="xc" refs="nig coa jet pla lea sil"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Night" shortname="nig">
		<UNIQUENAME name="night" />
		<UNIQUENAME name="knight" />
		<UNIQUENAME name="son" />
		<ADJACENCY type="xc" refs="bro umb obs coa mer sil"/>
	</PROVINCE>
	<PROVINCE fullname="Obsidian" shortname="obs">
		<UNIQUENAME name="obsid" />
		<ADJACENCY type="mv" refs="ebo coa"/>
		<ADJACENCY type="xc" refs="ebo umb nig coa"/>
	</PROVINCE>
	<PROVINCE fullname="Paper" shortname="pap">
		<ADJACENCY type="mv" refs="cha gho hot cry ink jet"/>
		<ADJACENCY type="xc" refs="pla cha jet"/>
	</PROVINCE>
	<PROVINCE fullname="Gulf of Platinum" shortname="pla">
		<UNIQUENAME name="plat" />
		<UNIQUENAME name="platinum" />
		<UNIQUENAME name="gop" />
		<UNIQUENAME name="gulfofp" />
		<UNIQUENAME name="pl" />
		<ADJACENCY type="xc" refs="pap cha lea mer jet"/>
	</PROVINCE>
	<PROVINCE fullname="Raven" shortname="rav">
		<UNIQUENAME name="rave" />
		<UNIQUENAME name="crow" />
		<ADJACENCY type="mv" refs="ebo ink jet"/>
		<ADJACENCY type="xc" refs="ebo umb haz ink"/>
	</PROVINCE>
	<PROVINCE fullname="Bay of Roses" shortname="ros">
		<UNIQUENAME name="rose" />
		<UNIQUENAME name="roses" />
		<UNIQUENAME name="bor" />
		<UNIQUENAME name="bayofr" />
		<ADJACENCY type="xc" refs="hot fir car che gho"/>
	</PROVINCE>
	<PROVINCE fullname="Royal" shortname="roy">
		<UNIQUENAME name="ryl" />
		<ADJACENCY type="mv" refs="azu sap cob cer"/>
		<ADJACENCY type="xc" refs="azu ind sap"/>
	</PROVINCE>
	<PROVINCE fullname="Ruby" shortname="rub">
		<ADJACENCY type="mv" refs="fir cri hot mar col"/>
		<ADJACENCY type="xc" refs="mar vio mau col"/>
	</PROVINCE>
	<PROVINCE fullname="Saffron" shortname="saf">
		<UNIQUENAME name="saff" />
		<ADJACENCY type="mv" refs="sul sun ink cry col cob"/>
		<ADJACENCY type="xc" refs="eme sul cob"/>
	</PROVINCE>
	<PROVINCE fullname="Sapphire" shortname="sap">
		<UNIQUENAME name="sapp" />
		<UNIQUENAME name="saph" />
		<UNIQUENAME name="saphire" />
		<ADJACENCY type="mv" refs="roy cer"/>
		<ADJACENCY type="xc" refs="roy ind aqu cer"/>
	</PROVINCE>
	<PROVINCE fullname="Sepiatic Sea" shortname="sep">
		<UNIQUENAME name="sepia" />
		<ADJACENCY type="xc" refs="but lem sun haz umb bro"/>
	</PROVINCE>
	<PROVINCE fullname="Silver" shortname="sil">
		<UNIQUENAME name="sliver" />
		<UNIQUENAME name="ag" />
		<ADJACENCY type="mv" refs="sil"/>
		<ADJACENCY type="xc" refs="lea ice mer nig"/>
	</PROVINCE>
	<PROVINCE fullname="Snow" shortname="sno">
		<ADJACENCY type="mv" refs="gho ala ivo"/>
		<ADJACENCY type="xc" refs="ala che ice gho"/>
	</PROVINCE>
	<PROVINCE fullname="Sulphur" shortname="sul">
		<UNIQUENAME name="sulfur" />
		<ADJACENCY type="mv" refs="gol saf sun"/>
		<ADJACENCY type="xc" refs="gol cya eme saf"/>
	</PROVINCE>
	<PROVINCE fullname="Sunshine" shortname="sun">
		<UNIQUENAME name="sunday" />
		<ADJACENCY type="mv" refs="sul gol saf lem ink"/>
		<ADJACENCY type="xc" refs="lem sep haz ink"/>
	</PROVINCE>
	<PROVINCE fullname="Topaz" shortname="top">
		<ADJACENCY type="mv" refs="gol lem"/>
		<ADJACENCY type="xc" refs="gol cya but lem"/>
	</PROVINCE>
	<PROVINCE fullname="Sea of Umber" shortname="umb">
		<UNIQUENAME name="umber" />
		<UNIQUENAME name="sou" />
		<UNIQUENAME name="cucumber" />
		<UNIQUENAME name="umberhulk" />
		<ADJACENCY type="xc" refs="haz rav ebo obs nig bro sep"/>
	</PROVINCE>
	<PROVINCE fullname="Vermillion" shortname="ver">
		<UNIQUENAME name="verm" />
		<UNIQUENAME name="vermin" />
		<ADJACENCY type="mv" refs="cri mar"/>
		<ADJACENCY type="xc" refs="cri car lav mar"/>
	</PROVINCE>
	<PROVINCE fullname="Violet Sea" shortname="vio">
		<UNIQUENAME name="violet" />
		<ADJACENCY type="xc" refs="lav mar rub mau ind mag"/>
	</PROVINCE>
</PROVINCES>
